### ISSUE TITLE
THE ANSWER TO LIFE, THE UNIVERSE AND EVERYTHING ?

### ISSUE THREAD

**Issue by laurentperrinet** [bicv/POLO#1]
Je pense que c’est entre 40 et 44. Vous en pensez quoi?

**Comment by laurentperrinet** [comment]
@gdbmanu ?

**Comment by gdbmanu** [comment]
Je laisse Julia répondre à cette question de geek!
 indice : https://en.wikipedia.org/wiki/The_Hitchhiker%27s_Guide_to_the_Galaxy

**Comment by laurentperrinet** [comment]
ou google?
https://www.google.com/search?q=THE%20ANSWER%20TO%20LIFE%2C%20THE%20UNIVERSE%20AND%20EVERYTHING%20%3F

**Comment by laurentperrinet** [comment]
ok, tout le monde est connecté!
